# Created 2018-06-28 Thu 21:55
#+TITLE: README
Easy Org Ensime (eoe) aims to make literate programming work again for
Scala. With this mode you can define a custom build.sbt file, run
=eoe-run= and use org-mode for literate programming in Scala.

* Installation Instructions
1. Install dependencies.
   1. Install org-mode using M-x package-install org-plus-contrib
   2. Install ensime using M-x package-install ensime
   3. Install sbt in your distribution: https://www.scala-sbt.org/1.0/docs/Setup.html
   4. sbt-ensime plugin (???)
   5. async.el (???)
2. Evaluate =easy-org-ensime.el= in Emacs
3. Define your build.sbt in the =eoe-dir= (by default it is "/tmp")

   #+BEGIN_SRC scala
     lazy val root = (project in file(".")).
       settings(
         inThisBuild(List(
           libraryDependencies += "org.scalaz" %% "scalaz-core" % "7.2.25",
           scalaVersion := "2.12.6",
           version := "0.1.0-SNAPSHOT")),
         name := "test"
       )
   #+END_SRC

4. Then run =(eoe-run)=
5. Check org-mode can now call scala fragments by calling C-c C-c on the following block:

   #+BEGIN_SRC scala
   1+1
   #+END_SRC

Note that many things need to be done to make this library cooler:
check (and contribute please) to the issue tracker.

Enjoy literate programming!
